//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.26 at 10:28:58 AM CET 
//

package eu.learnpad.or.rest.data.kbprocessing;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for KBProcessingStatusType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="KBProcessingStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IN PROGRESS"/>
 *     &lt;enumeration value="NEVER STARTED"/>
 *     &lt;enumeration value="COMPLETED"/>
 *     &lt;enumeration value="ABORTED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "KBProcessingStatusType")
@XmlEnum
public enum KBProcessingStatusType {

	@XmlEnumValue("IN PROGRESS") IN_PROGRESS("IN PROGRESS"), @XmlEnumValue("NEVER STARTED") NEVER_STARTED(
			"NEVER STARTED"), COMPLETED("COMPLETED"), ABORTED("ABORTED");
	private final String value;

	KBProcessingStatusType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static KBProcessingStatusType fromValue(String v) {
		for (KBProcessingStatusType c : KBProcessingStatusType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}
}