#!/usr/bin/env bash
cd $( dirname "${BASH_SOURCE[0]}")
{
    lp-dash-adoxx-cockpit/out/start > lp-dash-adoxx-cockpit.log 2>&1
    java -Xdebug \
	-Xrunjdwp:transport=dt_socket,address=9999,server=y,suspend=n \
	-Dconfig.file.location="config/componentMarche.properties" \
        -jar lp-dash-bridge-1.0-SNAPSHOT.jar > lp-dash-bridge-1.0-SNAPSHOT.log 2>&1
}&
