#!/usr/bin/env bash
cd $( dirname "${BASH_SOURCE[0]}")
{
##    lp-dash-adoxx-cockpit/out/start > lp-dash-adoxx-cockpit.log 2>&1
    java -jar lp-dash-bridge-1.0-SNAPSHOT.jar > lp-dash-bridge-1.0-SNAPSHOT.log 2>&1
}&
