#!/usr/bin/env bash

### VARIABLES ###

# This is the directory path to your component
declare -r __COMPONENT_PATH__="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
# This is the name of your component (must be the last part of ${__COMPONENT_PATH__}
declare -r __COMPONENT_NAME__="$( basename "${__COMPONENT_PATH__}" )"
# This is the path to your `out' directory
declare -r __OUT_PATH__="${__COMPONENT_PATH__}/out"
# These are path for the `start' and `stop' script that must be provided
declare -r __OUT_START_FILE__="${__OUT_PATH__}/start"
declare -r __OUT_STOP_FILE__="${__OUT_PATH__}/stop"
# This is a path to the optional file which list the needed dependencies to run the component
declare -r __OUT_RUNDEPS_FILE__="${__OUT_PATH__}/rundeps.txt"
# This is the path to the directory where you can optionally put some configuration files
declare -r __OUT_CONF_PATH__="${__OUT_PATH__}/etc"

declare -r __MVN_PROFILE__="--batch-mode -f ${__COMPONENT_PATH__}/pom.xml"

### BUILD ###
function component_build() {
    mvn ${__MVN_PROFILE__} clean
    # install local dependencies
    ls $__COMPONENT_PATH__/lib | grep .jar | xargs -I '{}' basename '{}' -0.0.1-SNAPSHOT.jar | xargs -I '{}' mvn install:install-file -Dfile=$__COMPONENT_PATH__/lib/{}-0.0.1-SNAPSHOT.jar -DgroupId=it.cnr.isti.labsedc -DartifactId={} -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
    # skip tests as we will do them in the component_test stage
    # Note: we install instead of just packaging since this project is a
    # dependency for other projects
    mvn ${__MVN_PROFILE__} install -Dmaven.test.skip=true
}

### TEST ###
function component_test() {
    mvn ${__MVN_PROFILE__} test
}

### INSTALL ###
# This is where you need to publish material into the `out' directory
function component_install() {
    mkdir -p ${__OUT_PATH__}
    cp "${__COMPONENT_PATH__}/scripts/start" "${__OUT_START_FILE__}"
    cp "${__COMPONENT_PATH__}/scripts/stop" "${__OUT_STOP_FILE__}"
    cp "${__COMPONENT_PATH__}/target/monitoring-"*"-jar-with-dependencies.jar" "${__OUT_PATH__}/"
    # There is no run dependencies for this component
    #cp <path_to>/rundeps.txt ${__OUT_RUNDEPS_FILE__}
    # These is no configuration file to copy
    #cp <path_to>/file.cfg ${__OUT_CONF_PATH__}/

    cp "${__COMPONENT_PATH__}/systemSettings" "${__OUT_PATH__}/"
    cp -r "${__COMPONENT_PATH__}/configFiles" "${__OUT_PATH__}/"
    cp -r "${__COMPONENT_PATH__}/data" "${__OUT_PATH__}/"
    if [ -n "$1" -a -d "${__COMPONENT_PATH__}/deployment/$1" ]
            then
                cp "${__COMPONENT_PATH__}/deployment/$1/environmentFile" \
                   "${__OUT_PATH__}/configFiles/."
            fi
}
