import eu.learnpad.simulator.mon.event.GlimpseBaseEventAbstract; 
import eu.learnpad.simulator.mon.event.GlimpseBaseEventBPMN; 
import eu.learnpad.sim.rest.event.impl.SimulationStartEvent; 
import eu.learnpad.sim.rest.event.impl.SimulationEndEvent; 
import eu.learnpad.sim.rest.event.impl.ProcessStartEvent; 
import eu.learnpad.sim.rest.event.impl.ProcessEndEvent; 
import eu.learnpad.sim.rest.event.impl.TaskStartEvent; 
import eu.learnpad.sim.rest.event.impl.TaskFailedEvent; 
import eu.learnpad.sim.rest.event.impl.TaskEndEvent; 
import eu.learnpad.sim.rest.event.impl.SessionScoreUpdateEvent; 
import eu.learnpad.sim.rest.event.EventType;
import eu.learnpad.simulator.mon.manager.ResponseDispatcher; 
import eu.learnpad.simulator.mon.manager.RestNotifier; 
        
declare GlimpseBaseEventBPMN
    @role( event )
    @timestamp( timeStamp )
end 

rule "FirstScenario"
no-loop true
salience 20
dialect "java"

when
	$0Event : GlimpseBaseEventBPMN(this.isConsumed == false, this.getEvent.type == EventType.PROCESS_START.toString(), 			this.isException == false);
	$1Event : GlimpseBaseEventBPMN(this.isConsumed == false, this.getEvent.type == EventType.SESSION_SCORE_UPDATE.toString(), 	this.isException == false, this after $0Event);
	$2Event : GlimpseBaseEventBPMN(this.isConsumed == false, this.getEvent.type == EventType.TASK_END.toString(), 				this.isException == false, this.getEventName == "Service Conference Invitation", this after $1Event);
	$3Event : GlimpseBaseEventBPMN(this.isConsumed == false, this.getEvent.type == EventType.PROCESS_END.toString(), 			this.isException == false, this after $2Event);

then 
	$0Event.setConsumed(true); 
	update($0Event);
	retract($0Event);
	$1Event.setConsumed(true); 
	update($1Event);
	retract($1Event);
	$2Event.setConsumed(true); 
	update($2Event);
	retract($2Event);
	$3Event.setConsumed(true); 
	update($3Event);
	retract($3Event);
	ResponseDispatcher.saveAndNotifyLearnersScore("##LEARNERSINVOLVEDID##", "FirstScenario", drools.getRule().getName(), (SessionScoreUpdateEvent)$1Event.getEvent());
end