//
/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 01:04:00 PM CET 
//


package eu.learnpad.mv.rest.data;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UnderstandabilityResult }
     * 
     */
    public UnderstandabilityResult createUnderstandabilityResult() {
        return new UnderstandabilityResult();
    }

    /**
     * Create an instance of {@link FormalVerificationResult }
     * 
     */
    public FormalVerificationResult createFormalVerificationResult() {
        return new FormalVerificationResult();
    }

    /**
     * Create an instance of {@link VerificationResults }
     * 
     */
    public VerificationResults createVerificationResults() {
        return new VerificationResults();
    }

    /**
     * Create an instance of {@link FormalVerificationResult.CounterExampleTrace }
     * 
     */
    public FormalVerificationResult.CounterExampleTrace createFormalVerificationResultCounterExampleTrace() {
        return new FormalVerificationResult.CounterExampleTrace();
    }

    /**
     * Create an instance of {@link UnderstandabilityResult.Guidelines }
     * 
     */
    public UnderstandabilityResult.Guidelines createUnderstandabilityResultGuidelines() {
        return new UnderstandabilityResult.Guidelines();
    }

    /**
     * Create an instance of {@link UnderstandabilityResult.Guidelines.Guideline }
     * 
     */
    public UnderstandabilityResult.Guidelines.Guideline createUnderstandabilityResultGuidelinesGuideline() {
        return new UnderstandabilityResult.Guidelines.Guideline();
    }

    /**
     * Create an instance of {@link UnderstandabilityResult.Guidelines.Guideline.Elements }
     * 
     */
    public UnderstandabilityResult.Guidelines.Guideline.Elements createUnderstandabilityResultGuidelinesGuidelineElements() {
        return new UnderstandabilityResult.Guidelines.Guideline.Elements();
    }

    /**
     * Create an instance of {@link ErrorResult }
     * 
     */
    public ErrorResult createErrorResult() {
        return new ErrorResult();
    }

    /**
     * Create an instance of {@link VerificationResults.Results }
     * 
     */
    public VerificationResults.Results createVerificationResultsResults() {
        return new VerificationResults.Results();
    }

    /**
     * Create an instance of {@link FormalVerificationResult.CounterExampleTrace.Step }
     * 
     */
    public FormalVerificationResult.CounterExampleTrace.Step createFormalVerificationResultCounterExampleTraceStep() {
        return new FormalVerificationResult.CounterExampleTrace.Step();
    }

    /**
     * Create an instance of {@link UnderstandabilityResult.Guidelines.Guideline.Elements.ElementID }
     * 
     */
    public UnderstandabilityResult.Guidelines.Guideline.Elements.ElementID createUnderstandabilityResultGuidelinesGuidelineElementsElementID() {
        return new UnderstandabilityResult.Guidelines.Guideline.Elements.ElementID();
    }

}
