#!/usr/bin/env bash
cd $( dirname "${BASH_SOURCE[0]}")
{
	./lp-ca-ui/start > lp-ca-ui.log
	java -Xdebug \
	-Xrunjdwp:transport=dt_socket,address=5432,server=y,suspend=n \
	-Dconfig.file.location="configMarche.properties" -jar lp-content-analysis.jar > analysis.log 2>&1
	
}&
