package eu.learnpad.sim.rest.event;

public enum ScoreType {
	SESSION_SCORE, ABSOLUTE_SESSION_SCORE, BP_SCORE, RELATIVE_BP_SCORE, BP_COVERAGE, ABSOLUTE_BP_SCORE, GLOBAL_SCORE, RELATIVE_GLOBAL_SCORE, ABSOLUTE_GLOBAL_SCORE;
}
